version: '3'
services:

  db:
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    image: kacperszo/novschola-db:1.0
    environment:
      - MYSQL_DATABASE=novschola
      - MYSQL_RANDOM_ROOT_PASSWORD='yes'
      - MYSQL_USER=novschola
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - /mysql_data
  api:
    restart: on-failure
    volumes:
      - /tmp
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
    ports:
    - 8080:8080
    environment:
      - jwtSecret=${JWT_SECRET}
      - smtpPassword=${SMTP_PASSWORD}
      - smtpUsername=${SMTP_USERNAME}
      - smtpHost=${SMTP_HOST}
      - smtpPort=${SMTP_PORT}
      - mysqlUsername=novschola
      - mysqlPassword=${DB_PASSWORD}
      - mysqlPort=3306
      - mysqlHost=db
      - mysqlName=novschola
      - startDelay=180
    depends_on:
      - db